SET COLSEP ',' 
SET NEWPAGE 0
SET LINESIZE 1000
SET PAGESIZE 0
SET ECHO OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET TERMOUT OFF;
CONNECT DP_PROD/presc1ent@KCMSV007
SET TERMOUT ON;

WHENEVER SQLERROR EXIT SQL.SQLCODE

--OUTPUT TO FILE
SET TERMOUT OFF
spool 'tmp.csv'

select * from dp_prod.pyramid_mstr

SELECT *
FROM (
  SELECT
    pm.PROD_NO as ITEM, 
    CASE WHEN db.PERIOD_ID - pyr.PERIOD_END_ID < 1 THEN 1 ELSE db.PERIOD_ID - pyr.PERIOD_END_ID END as RelWk,
    db.DEMAND_VALUE as OrderQuantity
  FROM DP_PROD.DEMAND_BUCKET db
  INNER JOIN DP_PROD.DEMAND_ENTITY de ON de.DEMAND_ENTITY_ID=db.DEMAND_ENTITY_ID
  INNER JOIN DP_PROD.PROD_MSTR pm ON pm.PROD_ID=de.PROD_ID
  CROSS JOIN (SELECT PERIOD_END_ID FROM DP_PROD.PYRAMID_MSTR WHERE PYRAMID_ID=1) pyr
  WHERE db.DEMAND_TYPE_CD = 2 AND db.DEMAND_VALUE > 0
) t
PIVOT (  
  SUM(OrderQuantity)
  FOR RelWk IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52)
) pvt
ORDER BY ITEM;

spool off;

SET TERMOUT ON;
prompt Completed spool to output file.;

COMMIT;
EXIT;
/



