SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

WITH SEAS_ITEM (ITEM,SEAS) AS (
	SELECT ITEM,SEAS
	FROM ( SELECT ITEM,SEAS,ROW_NUMBER() OVER (PARTITION BY ITEM ORDER BY SEAS) as ROW_NUM
		     FROM (SELECT DISTINCT ITEM,SEAS FROM SEAS_CUST_PROG) scp ) t 
  WHERE ROW_NUM = 1
),
ITEM_PROD_DATES (ITEM,SEAS,BEG_PROD_DT,END_PROD_DT) as (
	SELECT ITEM,si.SEAS,s.BEG_PROD_DT,s.END_PROD_DT
	FROM SEAS_ITEM si JOIN SEAS s ON s.SEAS=si.SEAS
)
SELECT ipp.ITEM,SUM(ipp.ACT_PROD_QTY) as PTD --,ipd.SEAS
FROM ITEM_PLANT_PROD ipp
JOIN ITEM_PROD_DATES ipd ON ipd.ITEM=ipp.ITEM AND ipp.PROD_DT BETWEEN ipd.BEG_PROD_DT AND ipd.END_PROD_DT
GROUP BY ipp.ITEM --,ipd.SEAS







