SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

WITH SEAS_SC (SEAS,SC,BEG_PROD_DT,END_PROD_DT) AS (
	SELECT s.SEAS,st.SELECTION_CD,s.BEG_PROD_DT,s.END_PROD_DT
	FROM SEAS s JOIN SEAS_TYPE st ON st.SEAS_TYPE=s.SEAS_TYPE
	WHERE s.ACTIVE = 1 AND st.SELECTION_CD IN('C','V','E','F','M','D')
)
SELECT ipp.ITEM,SUM(ipp.ACT_PROD_QTY) PTD
FROM ITEM_PLANT_PROD ipp
JOIN ITEM itm ON itm.ITEM=ipp.ITEM
JOIN SEAS_SC s ON s.SC=itm.SELECTION_CD AND ipp.PROD_DT BETWEEN s.BEG_PROD_DT AND s.END_PROD_DT
WHERE ACT_PROD_QTY > 0
GROUP BY ipp.ITEM;
